version: "3"

services:
 mongodb:
   image: mongo
   volumes:
     - ./db-data:/data/db
   #environment:
   #  MONGO_INITDB_ROOT_USERNAME: "$(MONGO_USERNAME)"
   #  MONGO_INITDB_ROOT_PASSWORD: "$(MONGO_PASSWORD)"
