version: "3"

services:
 mongodb:
   image: mongo
   volumes:
     - ./db-data:/data/db
   #environment:
   #  MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
   #  MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
 
 node:
   build:
     context: .
     dockerfile: ./docker/node/Dockerfile
   command: node server.js
   ports:
     - "80:80"
     - "5000:5000"
   depends_on:
     - "mongodb"
   links:
     - "mongodb"
   environment:
     MONGODB_URI: "${MONGODB_URI}"
     PORT: "${PORT}"
